spin_version = "1"
authors = ["Stefan Draskoci <s.draskoci@reply.com>"]
description = "Ratings service"
name = "ratings"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "ratings"
source = "main.wasm"
allowed_http_hosts = [ "insecure:allow-all" ]
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
