details:
  runtimeClassName: wasmtime-spin
  image:
    name: ghcr.io/liquid-reply/bookinfo/details
    tag: main
    pullSecret: ghcr
  port: 80

ratings:
  runtimeClassName:
  image:
    name: docker.io/istio/examples-bookinfo-ratings-v1
    tag: 1.17.0
  port: 9080

reviews:
  runtimeClassName: wasmtime-spin
  image:
    name: ghcr.io/liquid-reply/bookinfo/reviews
    tag: main
    pullSecret: ghcr
  port: 80

productpage:
  runtimeClassName:
  image:
    name: docker.io/istio/examples-bookinfo-productpage-v1
    tag: 1.17.0
  port: 9080
