name: bookinfo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-reviews:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
        rustup target add wasm32-wasi
        cd bookinfo/reviews
        cargo build --target wasm32-wasi --release
    - name: Upload wasm artifact
      uses: actions/upload-artifact@v3
      with:
        name: reviews.wasm
        path: bookinfo/reviews/target/wasm32-wasi/release/reviews.wasm

  build-oci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/liquid-reply/bookinfo
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        context: bookinfo
        file: bookinfo/Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
