name: bookinfo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-reviews:
    runs-on: ubuntu-latest
    container: rust:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
        rustup target add wasm32-wasi
        cd bookinfo/reviews
        cargo build --target wasm32-wasi --release
    - name: Upload wasm artifact
      uses: actions/upload-artifact@v3
      with:
        name: reviews.wasm
        path: bookinfo/reviews/target/wasm32-wasi/release/reviews.wasm

  build-details:
    runs-on: ubuntu-latest
    container: tinygo/tinygo-dev:latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: bash
      run: |
        cd bookinfo/details/details
        go mod tidy
        GOFLAGS="-buildvcs=false" tinygo build -target=wasi -gc=leaking -no-debug -o details.wasm .
    - name: Upload wasm artifact
      uses: actions/upload-artifact@v3
      with:
        name: details.wasm
        path: bookinfo/details/details/details.wasm

  build-oci:
    runs-on: ubuntu-latest
    needs: [build-reviews, build-details]
    steps:
    - uses: actions/checkout@v3
    - name: Download all wasm artifacts
      uses: actions/download-artifact@v3
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
